import Navbar from "./components/Navbar";
import { Josefin_Sans } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";

const josefin = Josefin_Sans({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "SolutionSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefin.className} font-medium`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
